//! C 头文件生成器
//!
//! 将 `export "C" { ... }` 块转换为标准 C 头文件 (`.h`)。
//!
//! 类型映射遵循 [spec.md 3.9.3 类型映射表](../../../docs/spec.md):
//! - `i32/i64/u32/u64/usize` → `int32_t/int64_t/uint32_t/uint64_t/size_t`
//! - `f32/f64` → `float/double`
//! - `bool` → `bool`(`<stdbool.h>`)
//! - `str` → `const char*`
//! - `void` / `()` → `void`
//! - `*mut T` → `T*`
//! - 其他命名类型 → 该名称(假设用户已在 C 侧定义)

use crate::{Generator, TypeMapper};
use linkc_parser::{FnSignature, TypeAnnotation};
use std::fmt::Write;

/// C 头文件生成器
pub struct CGenerator;

impl TypeMapper for CGenerator {
    fn map_type(&self, ann: &TypeAnnotation) -> String {
        match ann {
            TypeAnnotation::Void | TypeAnnotation::Unit => "void".to_string(),
            TypeAnnotation::Bool => "bool".to_string(),
            TypeAnnotation::I8 => "int8_t".to_string(),
            TypeAnnotation::I16 => "int16_t".to_string(),
            TypeAnnotation::I32 => "int32_t".to_string(),
            TypeAnnotation::I64 => "int64_t".to_string(),
            TypeAnnotation::U8 => "uint8_t".to_string(),
            TypeAnnotation::U16 => "uint16_t".to_string(),
            TypeAnnotation::U32 => "uint32_t".to_string(),
            TypeAnnotation::U64 => "uint64_t".to_string(),
            TypeAnnotation::USize => "size_t".to_string(),
            TypeAnnotation::F32 => "float".to_string(),
            TypeAnnotation::F64 => "double".to_string(),
            TypeAnnotation::Str => "const char*".to_string(),
            TypeAnnotation::Ptr(inner) => format!("{}*", self.map_type(inner)),
            TypeAnnotation::Named(s) => s.clone(),
            TypeAnnotation::Stream(inner) => {
                // C 侧没有 stream 概念,降级为指向首元素的指针 + 长度(由调用方约定)
                // 这里仅给出提示性类型
                format!("/* stream<{}> */ void*", self.map_type(inner))
            }
        }
    }
}

impl Generator for CGenerator {
    fn generate(
        &self,
        module_name: &str,
        module_path: Option<&str>,
        decls: &[FnSignature],
    ) -> String {
        let mut out = String::new();
        let guard = format!("LINK_{}_H", module_name.to_uppercase()
            .chars()
            .map(|c| if c.is_alphanumeric() { c } else { '_' })
            .collect::<String>());

        // 文件头注释
        let _ = writeln!(out, "/*");
        let _ = writeln!(out, " * {}  —— Auto-generated by `link bindgen --lang c`", module_name);
        let _ = writeln!(out, " * DO NOT EDIT MANUALLY.");
        if let Some(path) = module_path {
            let _ = writeln!(out, " * Source module: {}", path);
        }
        let _ = writeln!(out, " */");
        let _ = writeln!(out);

        // include guard
        let _ = writeln!(out, "#ifndef {}", guard);
        let _ = writeln!(out, "#define {}", guard);
        let _ = writeln!(out);

        // 标准头文件
        let _ = writeln!(out, "#include <stdint.h>");
        let _ = writeln!(out, "#include <stddef.h>");
        let _ = writeln!(out, "#include <stdbool.h>");
        let _ = writeln!(out);

        // extern "C" 兼容 C++
        let _ = writeln!(out, "#ifdef __cplusplus");
        let _ = writeln!(out, "extern \"C\" {{");
        let _ = writeln!(out, "#endif");
        let _ = writeln!(out);

        // 函数声明
        for sig in decls {
            let ret = sig.return_type.as_ref()
                .map(|t| self.map_type(t))
                .unwrap_or_else(|| "void".to_string());
            let params = if sig.params.is_empty() {
                "void".to_string()
            } else {
                sig.params.iter()
                    .map(|(name, ty)| format!("{} {}", self.map_type(ty), name))
                    .collect::<Vec<_>>()
                    .join(", ")
            };
            if sig.is_async {
                let _ = writeln!(out, "// async fn {}({});", sig.name, params);
            }
            let _ = writeln!(out, "{} {}({});", ret, sig.name, params);
            let _ = writeln!(out);
        }

        let _ = writeln!(out, "#ifdef __cplusplus");
        let _ = writeln!(out, "}}  // extern \"C\"");
        let _ = writeln!(out, "#endif");
        let _ = writeln!(out);
        let _ = writeln!(out, "#endif  // {}", guard);
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use linkc_parser::{FnSignature, TypeAnnotation};

    fn sig(name: &str, params: Vec<(&str, TypeAnnotation)>, ret: Option<TypeAnnotation>) -> FnSignature {
        FnSignature {
            name: name.to_string(),
            params: params.into_iter().map(|(n, t)| (n.to_string(), t)).collect(),
            return_type: ret,
            is_async: false,
        }
    }

    #[test]
    fn generates_basic_header() {
        let gen = CGenerator;
        let decls = vec![
            sig("link_init", vec![], Some(TypeAnnotation::Bool)),
            sig("link_add", vec![("a", TypeAnnotation::I32), ("b", TypeAnnotation::I32)], Some(TypeAnnotation::I32)),
            sig("link_greet", vec![("name", TypeAnnotation::Str)], Some(TypeAnnotation::Str)),
            sig("link_shutdown", vec![], None),
        ];
        let out = gen.generate("my_module", Some("./my_module.link"), &decls);
        assert!(out.contains("#ifndef LINK_MY_MODULE_H"));
        assert!(out.contains("#define LINK_MY_MODULE_H"));
        assert!(out.contains("extern \"C\""));
        assert!(out.contains("bool link_init(void);"));
        assert!(out.contains("int32_t link_add(int32_t a, int32_t b);"));
        assert!(out.contains("const char* link_greet(const char* name);"));
        assert!(out.contains("void link_shutdown(void);"));
        assert!(out.contains("* Source module: ./my_module.link"));
    }

    #[test]
    fn maps_all_numeric_types() {
        let gen = CGenerator;
        assert_eq!(gen.map_type(&TypeAnnotation::I8), "int8_t");
        assert_eq!(gen.map_type(&TypeAnnotation::U64), "uint64_t");
        assert_eq!(gen.map_type(&TypeAnnotation::USize), "size_t");
        assert_eq!(gen.map_type(&TypeAnnotation::F32), "float");
        assert_eq!(gen.map_type(&TypeAnnotation::F64), "double");
        assert_eq!(gen.map_type(&TypeAnnotation::Str), "const char*");
        assert_eq!(gen.map_type(&TypeAnnotation::Bool), "bool");
        assert_eq!(gen.map_type(&TypeAnnotation::Void), "void");
        assert_eq!(gen.map_type(&TypeAnnotation::Unit), "void");
    }

    #[test]
    fn maps_pointer_and_named() {
        let gen = CGenerator;
        assert_eq!(gen.map_type(&TypeAnnotation::Ptr(Box::new(TypeAnnotation::I32))), "int32_t*");
        assert_eq!(gen.map_type(&TypeAnnotation::Named("RoomHandle".to_string())), "RoomHandle");
    }
}
