//! Python 类型存根生成器
//!
//! 将 `export "python" module "<name>" { ... }` 块转换为 Python 类型存根文件 (`.pyi`)。
//!
//! 类型映射:
//! - `i32/i64/u32/u64/usize/i8/i16/u8/u16` → `int`
//! - `f32/f64` → `float`
//! - `bool` → `bool`
//! - `str` → `str`
//! - `void` / `()` → `None`
//! - `*mut T` → `int` (作为指针地址)
//! - 命名类型 → 该名称(假设 Python 侧已定义或由 SDK 提供)
//! - `stream<T>` → `AsyncIterable[T]`
//! - `async fn` → 标记为 `async def`

use crate::{Generator, TypeMapper};
use linkc_parser::{FnSignature, TypeAnnotation};
use std::fmt::Write;

/// Python 类型存根生成器
pub struct PythonGenerator;

impl TypeMapper for PythonGenerator {
    fn map_type(&self, ann: &TypeAnnotation) -> String {
        match ann {
            TypeAnnotation::Void | TypeAnnotation::Unit => "None".to_string(),
            TypeAnnotation::Bool => "bool".to_string(),
            TypeAnnotation::I8 | TypeAnnotation::I16 | TypeAnnotation::I32 | TypeAnnotation::I64
            | TypeAnnotation::U8 | TypeAnnotation::U16 | TypeAnnotation::U32 | TypeAnnotation::U64
            | TypeAnnotation::USize => "int".to_string(),
            TypeAnnotation::F32 | TypeAnnotation::F64 => "float".to_string(),
            TypeAnnotation::Str => "str".to_string(),
            TypeAnnotation::Ptr(_) => "int".to_string(),  // 指针地址
            TypeAnnotation::Named(s) => s.clone(),
            TypeAnnotation::Stream(inner) => format!("AsyncIterable[{}]", self.map_type(inner)),
            TypeAnnotation::Ref(inner, _) => self.map_type(inner),
            TypeAnnotation::Generic(base, _) => self.map_type(base),
            TypeAnnotation::Array(elem, _) => format!("list[{}]", self.map_type(elem)),
            TypeAnnotation::Tuple(elems) => {
                if elems.is_empty() {
                    "tuple".to_string()
                } else {
                    let parts: Vec<String> = elems.iter()
                        .map(|e| self.map_type(e))
                        .collect();
                    format!("tuple[{}]", parts.join(", "))
                }
            }
        }
    }
}

impl Generator for PythonGenerator {
    fn generate(
        &self,
        module_name: &str,
        module_path: Option<&str>,
        decls: &[FnSignature],
    ) -> String {
        let mut out = String::new();

        // 文件头
        let _ = writeln!(out, "\"\"\"");
        let _ = writeln!(out, "{}  —— Auto-generated by `link bindgen --lang python`", module_name);
        let _ = writeln!(out, "DO NOT EDIT MANUALLY.");
        if let Some(path) = module_path {
            let _ = writeln!(out, "Source module: {}", path);
        }
        let _ = writeln!(out, "\"\"\"");
        let _ = writeln!(out);

        // 类型导入(async stream 支持)
        let needs_async = decls.iter().any(|d| d.is_async)
            || decls.iter().any(|d| d.return_type.as_ref()
                .map(|t| matches!(t, TypeAnnotation::Stream(_)))
                .unwrap_or(false));
        if needs_async {
            let _ = writeln!(out, "from typing import AsyncIterable");
            let _ = writeln!(out);
        }

        for sig in decls {
            let ret = sig.return_type.as_ref()
                .map(|t| self.map_type(t))
                .unwrap_or_else(|| "None".to_string());
            let params = sig.params.iter()
                .map(|(name, ty)| format!("{}: {}", sanitize_ident(name), self.map_type(ty)))
                .collect::<Vec<_>>()
                .join(", ");
            let prefix = if sig.is_async { "async " } else { "" };
            let _ = writeln!(out, "{}def {}({}) -> {}: ...", prefix, sanitize_ident(&sig.name), params, ret);
        }

        out
    }
}

/// Python 标识符净化:Link 中的合法标识符在 Python 中可能不合法
fn sanitize_ident(s: &str) -> String {
    // Python 关键字冲突时加下划线后缀
    let reserved = ["def", "class", "import", "from", "as", "return", "yield",
                    "async", "await", "if", "else", "elif", "while", "for",
                    "break", "continue", "pass", "None", "True", "False",
                    "and", "or", "not", "in", "is", "lambda", "global",
                    "nonlocal", "try", "except", "finally", "raise", "with"];
    if reserved.contains(&s) {
        format!("{}_", s)
    } else {
        s.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sig(name: &str, params: Vec<(&str, TypeAnnotation)>, ret: Option<TypeAnnotation>, is_async: bool) -> FnSignature {
        FnSignature {
            name: name.to_string(),
            params: params.into_iter().map(|(n, t)| (n.to_string(), t)).collect(),
            return_type: ret,
            is_async,
        }
    }

    #[test]
    fn generates_pyi_stub() {
        let gen = PythonGenerator;
        let decls = vec![
            sig("start_server", vec![("port", TypeAnnotation::U16)], Some(TypeAnnotation::Bool), false),
            sig("fetch_json", vec![("url", TypeAnnotation::Str)], Some(TypeAnnotation::Named("Any".to_string())), true),
            sig("shutdown", vec![], None, false),
        ];
        let out = gen.generate("link_game", Some("./game.link"), &decls);
        assert!(out.contains("\"\"\""));
        assert!(out.contains("def start_server(port: int) -> bool: ..."));
        assert!(out.contains("async def fetch_json(url: str) -> Any: ..."));
        assert!(out.contains("def shutdown() -> None: ..."));
        assert!(out.contains("Source module: ./game.link"));
    }

    #[test]
    fn maps_stream_return_type() {
        let gen = PythonGenerator;
        let decls = vec![
            sig("events", vec![], Some(TypeAnnotation::Stream(Box::new(TypeAnnotation::I32))), false),
        ];
        let out = gen.generate("ev", None, &decls);
        assert!(out.contains("from typing import AsyncIterable"));
        assert!(out.contains("def events() -> AsyncIterable[int]: ..."));
    }

    #[test]
    fn sanitizes_reserved_identifiers() {
        assert_eq!(sanitize_ident("class"), "class_");
        assert_eq!(sanitize_ident("normal"), "normal");
        assert_eq!(sanitize_ident("import"), "import_");
    }

    #[test]
    fn maps_basic_types() {
        let gen = PythonGenerator;
        assert_eq!(gen.map_type(&TypeAnnotation::I64), "int");
        assert_eq!(gen.map_type(&TypeAnnotation::F64), "float");
        assert_eq!(gen.map_type(&TypeAnnotation::Str), "str");
        assert_eq!(gen.map_type(&TypeAnnotation::Bool), "bool");
        assert_eq!(gen.map_type(&TypeAnnotation::Void), "None");
        assert_eq!(gen.map_type(&TypeAnnotation::Ptr(Box::new(TypeAnnotation::I32))), "int");
    }
}
