//! TypeScript 声明文件生成器
//!
//! 将 `export "typescript" module "<name>" { ... }` 块转换为 TypeScript 声明文件 (`.d.ts`)。
//!
//! 类型映射:
//! - 整数类型 → `number`
//! - `f32/f64` → `number`
//! - `bool` → `boolean`
//! - `str` → `string`
//! - `void` / `()` → `void`
//! - `*mut T` → `number` (指针地址)
//! - 命名类型 → 该名称
//! - `stream<T>` → `AsyncIterable<T>`
//! - `async fn` → 返回 `Promise<T>`

use crate::{Generator, TypeMapper};
use linkc_parser::{FnSignature, TypeAnnotation};
use std::fmt::Write;

/// TypeScript 声明文件生成器
pub struct TypeScriptGenerator;

impl TypeMapper for TypeScriptGenerator {
    fn map_type(&self, ann: &TypeAnnotation) -> String {
        match ann {
            TypeAnnotation::Void | TypeAnnotation::Unit => "void".to_string(),
            TypeAnnotation::Bool => "boolean".to_string(),
            TypeAnnotation::I8 | TypeAnnotation::I16 | TypeAnnotation::I32 | TypeAnnotation::I64
            | TypeAnnotation::U8 | TypeAnnotation::U16 | TypeAnnotation::U32 | TypeAnnotation::U64
            | TypeAnnotation::USize => "number".to_string(),
            TypeAnnotation::F32 | TypeAnnotation::F64 => "number".to_string(),
            TypeAnnotation::Str => "string".to_string(),
            TypeAnnotation::Ptr(_) => "number".to_string(),  // 指针地址
            TypeAnnotation::Named(s) => s.clone(),
            TypeAnnotation::Stream(inner) => format!("AsyncIterable<{}>", self.map_type(inner)),
            TypeAnnotation::Ref(inner, _) => self.map_type(inner),
            TypeAnnotation::Generic(base, _) => self.map_type(base),
            TypeAnnotation::Array(elem, _) => format!("{}[]", self.map_type(elem)),
            TypeAnnotation::Tuple(elems) => {
                let parts: Vec<String> = elems.iter()
                    .map(|e| self.map_type(e))
                    .collect();
                format!("[{}]", parts.join(", "))
            }
        }
    }
}

impl Generator for TypeScriptGenerator {
    fn generate(
        &self,
        module_name: &str,
        module_path: Option<&str>,
        decls: &[FnSignature],
    ) -> String {
        let mut out = String::new();

        // 文件头
        let _ = writeln!(out, "/**");
        let _ = writeln!(out, " * {}  —— Auto-generated by `link bindgen --lang typescript`", module_name);
        let _ = writeln!(out, " * DO NOT EDIT MANUALLY.");
        if let Some(path) = module_path {
            let _ = writeln!(out, " * Source module: {}", path);
        }
        let _ = writeln!(out, " */");
        let _ = writeln!(out);

        // 声明为模块
        let _ = writeln!(out, "declare module \"{}\" {{", module_name);

        // 函数声明
        for sig in decls {
            let ret = sig.return_type.as_ref()
                .map(|t| self.map_type(t))
                .unwrap_or_else(|| "void".to_string());
            let params = sig.params.iter()
                .map(|(name, ty)| format!("{}: {}", sanitize_ident(name), self.map_type(ty)))
                .collect::<Vec<_>>()
                .join(", ");

            // async fn 在 TS 中返回 Promise<T>
            // stream<T> 也用 AsyncIterable,async 的话用 Promise<AsyncIterable<T>>
            let ret_str = if sig.is_async {
                format!("Promise<{}>", ret)
            } else {
                ret
            };
            let _ = writeln!(out, "    export function {}({}): {};", sanitize_ident(&sig.name), params, ret_str);
        }

        let _ = writeln!(out, "}}");
        out
    }
}

/// TS 标识符净化:Link 中合法标识符在 TS 中可能冲突
fn sanitize_ident(s: &str) -> String {
    let reserved = ["break", "case", "catch", "class", "const", "continue", "debugger",
                    "default", "delete", "do", "else", "enum", "export", "extends",
                    "false", "finally", "for", "function", "if", "import", "in",
                    "instanceof", "new", "null", "return", "super", "switch", "this",
                    "throw", "true", "try", "typeof", "var", "void", "while", "with",
                    "as", "async", "await", "yield"];
    if reserved.contains(&s) {
        format!("{}_", s)
    } else {
        s.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sig(name: &str, params: Vec<(&str, TypeAnnotation)>, ret: Option<TypeAnnotation>, is_async: bool) -> FnSignature {
        FnSignature {
            name: name.to_string(),
            params: params.into_iter().map(|(n, t)| (n.to_string(), t)).collect(),
            return_type: ret,
            is_async,
        }
    }

    #[test]
    fn generates_dts_module() {
        let gen = TypeScriptGenerator;
        let decls = vec![
            sig("createRoom", vec![("maxPlayers", TypeAnnotation::U8)], Some(TypeAnnotation::Named("Room".to_string())), false),
            sig("fetchJson", vec![("url", TypeAnnotation::Str)], Some(TypeAnnotation::Named("JsonValue".to_string())), true),
            sig("shutdown", vec![], None, false),
        ];
        let out = gen.generate("link-game", Some("./game.link"), &decls);
        assert!(out.contains("declare module \"link-game\""));
        assert!(out.contains("export function createRoom(maxPlayers: number): Room;"));
        assert!(out.contains("export function fetchJson(url: string): Promise<JsonValue>;"));
        assert!(out.contains("export function shutdown(): void;"));
        assert!(out.contains("Source module: ./game.link"));
    }

    #[test]
    fn maps_stream_return_type() {
        let gen = TypeScriptGenerator;
        let decls = vec![
            sig("events", vec![], Some(TypeAnnotation::Stream(Box::new(TypeAnnotation::I32))), false),
        ];
        let out = gen.generate("ev", None, &decls);
        assert!(out.contains("export function events(): AsyncIterable<number>;"));
    }

    #[test]
    fn maps_basic_types() {
        let gen = TypeScriptGenerator;
        assert_eq!(gen.map_type(&TypeAnnotation::I64), "number");
        assert_eq!(gen.map_type(&TypeAnnotation::F64), "number");
        assert_eq!(gen.map_type(&TypeAnnotation::Str), "string");
        assert_eq!(gen.map_type(&TypeAnnotation::Bool), "boolean");
        assert_eq!(gen.map_type(&TypeAnnotation::Void), "void");
        assert_eq!(gen.map_type(&TypeAnnotation::Ptr(Box::new(TypeAnnotation::I32))), "number");
    }

    #[test]
    fn sanitizes_reserved_identifiers() {
        assert_eq!(sanitize_ident("class"), "class_");
        assert_eq!(sanitize_ident("function"), "function_");
        assert_eq!(sanitize_ident("normal"), "normal");
    }
}
