/*
 * link_sdk  —— Auto-generated by `link bindgen --lang c`
 * DO NOT EDIT MANUALLY.
 */

#ifndef LINK_LINK_SDK_H
#define LINK_LINK_SDK_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

bool link_init(void);

uint32_t link_create_room(uint8_t max_players);

bool link_join_room(uint32_t room_id, const char* player_name);

bool link_send_message(uint32_t room_id, const char* message);

uint32_t link_get_player_count(uint32_t room_id);

void link_shutdown(void);

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // LINK_LINK_SDK_H
