/**
 * link_sdk  —— Auto-generated by `link bindgen --lang typescript`
 * DO NOT EDIT MANUALLY.
 * Source module: link-game-sdk
 */

declare module "link_sdk" {
    export function createRoom(maxPlayers: number): number;
    export function joinRoom(roomId: number, name: string): boolean;
    export function broadcast(roomId: number, msg: string): void;
    export function fetchState(roomId: number): Promise<string>;
    export function playerCount(roomId: number): number;
}
