#!/usr/bin/env python3
# Generated by Link compiler - Python backend
import math
import time

class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def __repr__(self):
        return "Point(" + "x=" + str(self.x) + ", " + "y=" + str(self.y) + ")"

class Color:
    Red = "Red"
    Green = "Green"
    Blue = "Blue"
    @staticmethod
    def RGB(*args):
        return ("RGB", args)

def add(a, b):
    return (a + b)

def fib(n):
    if (n <= 1):
        return n
    return (fib((n - 1)) + fib((n - 2)))

def main():
    x = 42
    y = 3.14
    s = "hello"
    b = True
    xs = [1, 2, 3, 4, 5]
    print("=== Link -> Python Demo ===")
    print("x = {}".format(x))
    print("y = {}".format(y))
    print("s = {}".format(s))
    print("b = {}".format(b))
    print("xs = {}".format(xs))
    sum = add(3, 7)
    print("add(3, 7) = {}".format(sum))
    result = fib(10)
    print("fib(10) = {}".format(result))
    p = Point(x=1.0, y=2.0)
    print("point x = {}, y = {}".format(p.x, p.y))
    c = Color.Red
    _tmp1 = c
    if _tmp1 == Color.Red:
        print("red")
    elif _tmp1 == Color.Green:
        print("green")
    elif _tmp1 == Color.Blue:
        print("blue")
    else:
        print("other")
    total = 0
    for i in range(0, 10):
        total = (total + i)
    print("sum 0..10 = {}".format(total))


if __name__ == "__main__":
    main()
